### PR TITLE
improve docs, logging, fix integration-tests

### LINKED ISSUE #19: Use `eigensdk` instead of `eigen-*` crates

### PR DESCRIPTION
**Pull request by supernovahs**
- fixed integration-tests as per UAM
- fixed a bug to give permission to `slashOperator`
- removed `integration-tests` feature .
- Removed hardcode of stakes in aggregator.
- Docs and logs nits

closes #19

### CODE REVIEW

**Review by MegaRedHand — COMMENTED** [review]
Can you split this PR into two: one just updating the SDK version and making it compile, and another fixing the integration tests?

**Comment by supernovahs** [comment]
I'll open another PR for the sdk bump once this gets merged

File: integration-tests/src/lib.rs [hunk 1]
```diff
@@ -154,28 +156,24 @@ mod tests {
...
             let key_pair = BlsKeyPair::new(fr_key).unwrap();
-        dbg!(incredible_config.operator_set_id().unwrap());
-        let  e = register_for_operator_sets(incredible_config.operator_set_id().unwrap(),key_pair,incredible_config.registry_coordinator_addr().unwrap(),get_allocation_manager_address(ANVIL_HTTP_URL.to_string()).await,incredible_config.operator_pvt_key(),incredible_config.ecdsa_keystore_path(),incredible_config.ecdsa_keystore_password(),ANVIL_HTTP_URL,incredible_config.service_manager_addr().unwrap(),incredible_config.socket().to_string()).await.unwrap();
-        dbg!(e);
+        register_for_operator_sets(incredible_config.operator_set_id().unwrap(),key_pair,incredible_config.permission_controller_address().unwrap(),incredible_config.registry_coordinator_addr().unwrap(),get_allocation_manager_address(ANVIL_HTTP_URL.to_string()).await,incredible_config.operator_pvt_key(),incredible_config.ecdsa_keystore_path(),incredible_config.ecdsa_keystore_password(),ANVIL_HTTP_URL,incredible_config.service_manager_addr().unwrap(),incredible_config.socket().to_string()).await.unwrap();
```
Comment (MegaRedHand) [inline integration-tests/src/lib.rs:176]: Can we format this better?
